name: genome_diversity_spa
channels:
  - cruizperez
  - bioconda
  - conda-forge
  - ursky
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - _r-mutex
  - alsa-lib
  - bbmap
  - bcftools
  - binutils_impl_linux-64
  - binutils_linux-64
  - bowtie2
  - bwidget
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - curl
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fraggenescan
  - freetype
  - fribidi
  - gcc_impl_linux-64
  - gcc_linux-64
  - gdbm
  - gettext
  - gfortran_impl_linux-64
  - gfortran_linux-64
  - giflib
  - gmp
  - graphite2
  - gsl
  - gxx_impl_linux-64
  - gxx_linux-64
  - harfbuzz
  - hmmer
  - htslib
  - icu
  - idba
  - jpeg
  - kernel-headers_linux-64
  - krb5
  - lcms2
  - ld_impl_linux-64
  - libblas
  - libcblas
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgcc
  - libgcc-devel_linux-64
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libgomp
  - libiconv
  - liblapack
  - libnghttp2
  - libopenblas
  - libpng
  - libssh2
  - libstdcxx-devel_linux-64
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb
  - libxml2
  - lz4-c
  - make
  - maxbin2
  - metabat2
  - ncurses
  - ninja
  - numpy
  - openjdk
  - openssl
  - pango
  - parallel
  - pbzip2
  - pcre
  - pcre2
  - perl
  - perl-encode
  - perl-encode-locale
  - perl-exporter
  - perl-lwp-simple
  - perl-parent
  - pip
  - pixman
  - pthread-stubs
  - pycparser
  - pysam
  - python
  - python_abi
  - pytorch-cpu
  - r-base
  - r-bitops
  - r-catools
  - r-gplots
  - r-gtools
  - r-kernsmooth
  - readline
  - ruby
  - samtools
  - sed
  - setuptools
  - spades
  - sqlite
  - sysroot_linux-64
  - tar
  - tbb
  - tk
  - tktable
  - vamb
  - wheel
  - xorg-fixesproto
  - xorg-inputproto
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxfixes
  - xorg-libxi
  - xorg-libxrender
  - xorg-libxt
  - xorg-libxtst
  - xorg-recordproto
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yaml
  - zlib
  - zstd
